using System.ComponentModel.DataAnnotations;

namespace ProjectAkbas.Models
{
    public class mProformaMaliyet
    {
        [Key]
        public int IDD { get; set; }
        public decimal? A1StokMerkezDepoIsPlan { get; set; }
        public decimal? A1Topbasi { get; set; }
        public string? Aciklama { get; set; }
        public string? Aciklama1 { get; set; }
        public string? Aciklama2 { get; set; }
        public string? Aciklama3 { get; set; }
        public string? Aciklama4 { get; set; }
        public string? Aciklama5 { get; set; }
        public string? Aciklama6 { get; set; }
        public string? ActiveWear { get; set; }
        public decimal? AnkoleOzelIslem { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string? Atki1_Iplik4 { get; set; }
        public decimal? Atki1_Iplik4_Fire { get; set; }
        public string? Atki2_Iplik5 { get; set; }
        public decimal? Atki2_Iplik5_Fire { get; set; }
        public string? Atki3_Iplik6 { get; set; }
        public decimal? Atki3_Iplik6_Fire { get; set; }
        public string? BoyamaSekli { get; set; }
        public decimal? Cekme1 { get; set; }
        public decimal? Cekme2 { get; set; }
        public string? Cozgu1_Iplik1 { get; set; }
        public decimal? Cozgu1_Iplik1_Fire { get; set; }
        public string? Cozgu2_Iplik2 { get; set; }
        public decimal? Cozgu2_Iplik2_Fire { get; set; }
        public string? Cozgu3_Iplik3 { get; set; }
        public decimal? Cozgu3_Iplik3_Fire { get; set; }
        public string? Description { get; set; }
        public string? DesenVaryant { get; set; }
        public string? DokumaOrme { get; set; }
        public decimal? Dolar { get; set; }
        public decimal? En { get; set; }
        public decimal? Euro { get; set; }
        public decimal? Fire { get; set; }
        public string? FuarSFGoruntu { get; set; }
        public decimal? GenelUretimYurtdisi { get; set; }
        public decimal? GenelUretimYurtici { get; set; }
        public decimal? GenelYonetimYurtdisi { get; set; }
        public decimal? GenelYonetimYurtici { get; set; }
        public decimal? Gr { get; set; }
        public decimal? HamKumasFiyatiKg { get; set; }
        public decimal? HamKumasFiyatiKgTesvikli { get; set; }
        public decimal? HamKumasFiyatiMt { get; set; }
        public decimal? HamKumasFiyatiMtTesvikli { get; set; }
        public decimal? HamKumasFiyatiProforma { get; set; }
        public decimal? HamKumasFiyatiProformaTesvikli { get; set; }
        public decimal? HamKumasFiyatiProformaVergiyeEsas { get; set; }
        public string? HamKumasMensei { get; set; }
        public string? HamKumasMenseiTesvikli { get; set; }
        public decimal? HazirlikGrubu { get; set; }
        public string? Ip { get; set; }
        public decimal? IplikFire { get; set; }
        public decimal? IscilikOrmeMaliyeti { get; set; }
        public decimal? IscilikOrmeMaliyeti_Czg { get; set; }
        public string? Islem { get; set; }
        public string? IslemYeri { get; set; }
        public decimal? KaliteKontrol { get; set; }
        public DateTime? KayitTarihi { get; set; }
        public decimal? KgFiyati1 { get; set; }
        public decimal? KgFiyati11 { get; set; }
        public decimal? KgFiyati2 { get; set; }
        public decimal? KgFiyati22 { get; set; }
        public decimal? KgFiyati3 { get; set; }
        public decimal? KgFiyati33 { get; set; }
        public decimal? KgFiyati4 { get; set; }
        public decimal? KgFiyati44 { get; set; }
        public decimal? KgFiyati5 { get; set; }
        public decimal? KgFiyati55 { get; set; }
        public decimal? KgFiyati6 { get; set; }
        public decimal? KgFiyati66 { get; set; }
        public decimal? KomisyonOran { get; set; }
        public string? Kullanici { get; set; }
        public string? KumasKalitesi { get; set; }
        public string? KumasKodu { get; set; }
        public string? MalGrubu { get; set; }
        public decimal? Metre { get; set; }
        public decimal? MtKgYuzde1 { get; set; }
        public decimal? MtKgYuzde2 { get; set; }
        public decimal? MtKgYuzde3 { get; set; }
        public decimal? MtKgYuzde4 { get; set; }
        public decimal? MtKgYuzde5 { get; set; }
        public decimal? MtKgYuzde6 { get; set; }
        public string? MuadilKaliteGrubu { get; set; }
        public string? Musteri { get; set; }
        public string? MusteriTemsilcisi { get; set; }
        public decimal? NavlunKaraNakliyesi { get; set; }
        public string? NumuneKodu { get; set; }
        public string? OdemeSekli { get; set; }
        public decimal? ProfSFYurtdisiAAlt { get; set; }
        public decimal? ProfSFYurtdisiADip { get; set; }
        public decimal? ProfSFYurtdisiAUst { get; set; }
        public decimal? ProfSFYurtdisiBAlt { get; set; }
        public decimal? ProfSFYurtdisiBDip { get; set; }
        public decimal? ProfSFYurtdisiBUst { get; set; }
        public decimal? ProfSFYurtdisiCAlt { get; set; }
        public decimal? ProfSFYurtdisiCDip { get; set; }
        public decimal? ProfSFYurtdisiCUst { get; set; }
        public decimal? ProfSFYurtdisiDAlt { get; set; }
        public decimal? ProfSFYurtdisiDDip { get; set; }
        public decimal? ProfSFYurtdisiDUst { get; set; }
        public decimal? ProfSFYurtdisiEAlt { get; set; }
        public decimal? ProfSFYurtdisiEDip { get; set; }
        public decimal? ProfSFYurtdisiEUst { get; set; }
        public decimal? ProfSFYurtdisiFAlt { get; set; }
        public decimal? ProfSFYurtdisiFDip { get; set; }
        public decimal? ProfSFYurtdisiFUst { get; set; }
        public decimal? ProfSFYurtdisiGAlt { get; set; }
        public decimal? ProfSFYurtdisiGDip { get; set; }
        public decimal? ProfSFYurtdisiGUst { get; set; }
        public decimal? ProfSFYurtdisiHAlt { get; set; }
        public decimal? ProfSFYurtdisiHDip { get; set; }
        public decimal? ProfSFYurtdisiHUst { get; set; }
        public decimal? ProfSFYurtdisiIng { get; set; }
        public decimal? ProfSFYurtici { get; set; }
        public decimal? ProfSFYurticiIst { get; set; }
        public decimal? ProfSFYurticiKonf { get; set; }
        public string? Proses1 { get; set; }
        public decimal? Proses1_Dk { get; set; }
        public decimal? Proses1_Hiz { get; set; }
        public string? Proses1_Mak { get; set; }
        public decimal? Proses1_Mt { get; set; }
        public decimal? Proses1_Recete { get; set; }
        public decimal? Proses1_Sabit { get; set; }
        public string? Proses10 { get; set; }
        public decimal? Proses10_Dk { get; set; }
        public decimal? Proses10_Hiz { get; set; }
        public string? Proses10_Mak { get; set; }
        public decimal? Proses10_Mt { get; set; }
        public decimal? Proses10_Recete { get; set; }
        public decimal? Proses10_Sabit { get; set; }
        public string? Proses11 { get; set; }
        public decimal? Proses11_Dk { get; set; }
        public decimal? Proses11_Hiz { get; set; }
        public string? Proses11_Mak { get; set; }
        public decimal? Proses11_Mt { get; set; }
        public decimal? Proses11_Recete { get; set; }
        public decimal? Proses11_Sabit { get; set; }
        public string? Proses12 { get; set; }
        public decimal? Proses12_Dk { get; set; }
        public decimal? Proses12_Hiz { get; set; }
        public string? Proses12_Mak { get; set; }
        public decimal? Proses12_Mt { get; set; }
        public decimal? Proses12_Recete { get; set; }
        public decimal? Proses12_Sabit { get; set; }
        public string? Proses13 { get; set; }
        public decimal? Proses13_Dk { get; set; }
        public decimal? Proses13_Hiz { get; set; }
        public string? Proses13_Mak { get; set; }
        public decimal? Proses13_Mt { get; set; }
        public decimal? Proses13_Recete { get; set; }
        public decimal? Proses13_Sabit { get; set; }
        public string? Proses2 { get; set; }
        public decimal? Proses2_Dk { get; set; }
        public decimal? Proses2_Hiz { get; set; }
        public string? Proses2_Mak { get; set; }
        public decimal? Proses2_Mt { get; set; }
        public decimal? Proses2_Recete { get; set; }
        public decimal? Proses2_Sabit { get; set; }
        public string? Proses21 { get; set; }
        public decimal? Proses21_Dk { get; set; }
        public decimal? Proses21_Hiz { get; set; }
        public string? Proses21_Mak { get; set; }
        public decimal? Proses21_Mt { get; set; }
        public decimal? Proses21_Recete { get; set; }
        public decimal? Proses21_Sabit { get; set; }
        public string? Proses22 { get; set; }
        public decimal? Proses22_Dk { get; set; }
        public decimal? Proses22_Hiz { get; set; }
        public string? Proses22_Mak { get; set; }
        public decimal? Proses22_Mt { get; set; }
        public decimal? Proses22_Recete { get; set; }
        public decimal? Proses22_Sabit { get; set; }
        public string? Proses23 { get; set; }
        public decimal? Proses23_Dk { get; set; }
        public decimal? Proses23_Hiz { get; set; }
        public string? Proses23_Mak { get; set; }
        public decimal? Proses23_Mt { get; set; }
        public decimal? Proses23_Recete { get; set; }
        public decimal? Proses23_Sabit { get; set; }
        public string? Proses24 { get; set; }
        public decimal? Proses24_Dk { get; set; }
        public decimal? Proses24_Hiz { get; set; }
        public string? Proses24_Mak { get; set; }
        public decimal? Proses24_Mt { get; set; }
        public decimal? Proses24_Recete { get; set; }
        public decimal? Proses24_Sabit { get; set; }
        public string? Proses25 { get; set; }
        public decimal? Proses25_Dk { get; set; }
        public decimal? Proses25_Hiz { get; set; }
        public string? Proses25_Mak { get; set; }
        public decimal? Proses25_Mt { get; set; }
        public decimal? Proses25_Recete { get; set; }
        public decimal? Proses25_Sabit { get; set; }
        public string? Proses26 { get; set; }
        public decimal? Proses26_Dk { get; set; }
        public decimal? Proses26_Hiz { get; set; }
        public string? Proses26_Mak { get; set; }
        public decimal? Proses26_Mt { get; set; }
        public decimal? Proses26_Recete { get; set; }
        public decimal? Proses26_Sabit { get; set; }
        public string? Proses27 { get; set; }
        public decimal? Proses27_Dk { get; set; }
        public decimal? Proses27_Hiz { get; set; }
        public string? Proses27_Mak { get; set; }
        public decimal? Proses27_Mt { get; set; }
        public decimal? Proses27_Recete { get; set; }
        public decimal? Proses27_Sabit { get; set; }
        public string? Proses28 { get; set; }
        public decimal? Proses28_Dk { get; set; }
        public decimal? Proses28_Hiz { get; set; }
        public string? Proses28_Mak { get; set; }
        public decimal? Proses28_Mt { get; set; }
        public decimal? Proses28_Recete { get; set; }
        public decimal? Proses28_Sabit { get; set; }
        public string? Proses29 { get; set; }
        public decimal? Proses29_Dk { get; set; }
        public decimal? Proses29_Hiz { get; set; }
        public string? Proses29_Mak { get; set; }
        public decimal? Proses29_Mt { get; set; }
        public decimal? Proses29_Recete { get; set; }
        public decimal? Proses29_Sabit { get; set; }
        public string? Proses3 { get; set; }
        public decimal? Proses3_Dk { get; set; }
        public decimal? Proses3_Hiz { get; set; }
        public string? Proses3_Mak { get; set; }
        public decimal? Proses3_Mt { get; set; }
        public decimal? Proses3_Recete { get; set; }
        public decimal? Proses3_Sabit { get; set; }
        public string? Proses30 { get; set; }
        public decimal? Proses30_Dk { get; set; }
        public decimal? Proses30_Hiz { get; set; }
        public string? Proses30_Mak { get; set; }
        public decimal? Proses30_Mt { get; set; }
        public decimal? Proses30_Recete { get; set; }
        public decimal? Proses30_Sabit { get; set; }
        public string? Proses4 { get; set; }
        public decimal? Proses4_Dk { get; set; }
        public decimal? Proses4_Hiz { get; set; }
        public string? Proses4_Mak { get; set; }
        public decimal? Proses4_Mt { get; set; }
        public decimal? Proses4_Recete { get; set; }
        public decimal? Proses4_Sabit { get; set; }
        public string? Proses5 { get; set; }
        public decimal? Proses5_Dk { get; set; }
        public decimal? Proses5_Hiz { get; set; }
        public string? Proses5_Mak { get; set; }
        public decimal? Proses5_Mt { get; set; }
        public decimal? Proses5_Recete { get; set; }
        public decimal? Proses5_Sabit { get; set; }
        public string? Proses6 { get; set; }
        public decimal? Proses6_Dk { get; set; }
        public decimal? Proses6_Hiz { get; set; }
        public string? Proses6_Mak { get; set; }
        public decimal? Proses6_Mt { get; set; }
        public decimal? Proses6_Recete { get; set; }
        public decimal? Proses6_Sabit { get; set; }
        public string? Proses7 { get; set; }
        public decimal? Proses7_Dk { get; set; }
        public decimal? Proses7_Hiz { get; set; }
        public string? Proses7_Mak { get; set; }
        public decimal? Proses7_Mt { get; set; }
        public decimal? Proses7_Recete { get; set; }
        public decimal? Proses7_Sabit { get; set; }
        public string? Proses8 { get; set; }
        public decimal? Proses8_Dk { get; set; }
        public decimal? Proses8_Hiz { get; set; }
        public string? Proses8_Mak { get; set; }
        public decimal? Proses8_Mt { get; set; }
        public decimal? Proses8_Recete { get; set; }
        public decimal? Proses8_Sabit { get; set; }
        public string? Proses9 { get; set; }
        public decimal? Proses9_Dk { get; set; }
        public decimal? Proses9_Hiz { get; set; }
        public string? Proses9_Mak { get; set; }
        public decimal? Proses9_Mt { get; set; }
        public decimal? Proses9_Recete { get; set; }
        public decimal? Proses9_Sabit { get; set; }
        public string? ProsesKodu { get; set; }
        public string? Qualities { get; set; }
        public string? QualitiesGroup { get; set; }
        public string? SatisFiyati { get; set; }
        public string? SiparisMiktari { get; set; }
        public string? SiparisNo { get; set; }
        public int? SiraBenzerKumas { get; set; }
        public int? SiraUstAlt { get; set; }
        public string? SpecialEffect { get; set; }
        public decimal? Stok { get; set; }
        public string? Sustainable { get; set; }
        public string? TalepEden { get; set; }
        public string? VarisYeri { get; set; }
        public string? YarnDyed { get; set; }
        public decimal? YurtDisiDolarMetre { get; set; }
        public decimal? YurtdisiKomisyon { get; set; }
        public decimal? YurtdisiNakliyeNavlun { get; set; }
        public decimal? YurticiDolarMetre { get; set; }
        public decimal? YurticiKomisyon { get; set; }
        public decimal? YurticiNakliyeNavlun { get; set; }
        public string? ZeminRengi { get; set; }
    }
}
